--- # DEFAULT
config: default
fast_dev_run: false
do_train: true
do_predict: true
tags:
- bert
batch_size: 4
linearisation: ord_first
max_features: 50
model_base: bert-base-cased
output_root: models/exps_mentioned/
max_input_len: 512
num_epochs: 10
early_stopping_patience: 3
logging_steps: 100
device: cuda
resume_from_checkpoint: false
predict_batch_size: 4
save_total_limit: 1
augmented_ds: false