--- # ESSEL
config: essel
fast_dev_run: false
tags:
 - t5-base
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2

--- # ord first
config: ord_first
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2

--- # ft first
config: ft_first
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2

--- # ESSEL 2
config: essel_2
fast_dev_run: false
tags:
 - bart
batch_size: 8
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2

--- # ord first 2
config: ord_first_2
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
batch_size: 64
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2

--- # ft first 2
config: ft_first_2
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
batch_size: 64
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2

--- # ESSEL qa first
config: essel_qa
fast_dev_run: false
tags:
 - t5-base
 - qa pretrain
# batch_size: 8
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: models/qa/t5-base/silver-sky-30/checkpoint-30000
output_root: models/t5-base/
predict_batch_size: 2

--- # ord first qa first
config: ord_first_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - qa pretrain
# batch_size: 32
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: models/qa/t5-base/dark-bird-35/checkpoint-37500
output_root: models/t5-base/
predict_batch_size: 2

--- # ft first qa first
config: ft_first_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - qa pretrain
batch_size: 8
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: models/qa/t5-base/lunar-sponge-36/checkpoint-123000
output_root: models/t5-base/
predict_batch_size: 2

--- # ESSEL 2 qa first
config: essel_2_qa
fast_dev_run: false
tags:
 - bart
 - qa pretrain
# batch_size: 16
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: models/qa/bart-base/helpful-aardvark-21/checkpoint-6000
output_root: models/bart-base/
predict_batch_size: 2

--- # ord first 2 qa first
config: ord_first_2_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
 - qa pretrain
# batch_size: 16
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: models/qa/bart-base/warm-sky-22/checkpoint-18750
output_root: models/bart-base/
predict_batch_size: 2

--- # ft first 2 qa first
config: ft_first_2_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
 - qa pretrain
# batch_size: 8
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: models/qa/bart-base/chocolate-dust-23/checkpoint-18750
output_root: models/bart-base/
predict_batch_size: 2

--- # ESSEL 3
config: essel_3
fast_dev_run: false
tags:
 - t5-base
 - augmented
batch_size: 8
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # ord first 3
config: ord_first_3
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - augmented
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # ft first 3
config: ft_first_3
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - augmented
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # ESSEL 4
config: essel_4
fast_dev_run: false
tags:
 - bart
 - augmented
batch_size: 16
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ord first 4
config: ord_first_4
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
 - augmented
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ft first 4
config: ft_first_4
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
 - augmented
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ESSEL 3 qa
config: essel_3_qa
fast_dev_run: false
tags:
 - t5-base
 - augmented
 - qa pretrain
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # ord first 3 qa
config: ord_first_3_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - augmented
 - qa pretrain
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # ft first 3 qa
config: ft_first_3_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - augmented
 - qa pretrain
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # ESSEL 4 qa
config: essel_4_qa
fast_dev_run: false
tags:
 - bart
 - augmented
 - qa pretrain
# batch_size: 16
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ord first 4 qa
config: ord_first_4_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
 - augmented
 - qa pretrain
# batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ft first 4 qa
config: ft_first_4_qa
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
 - augmented
 - qa pretrain
# batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ESSEL 5
config: essel_5
fast_dev_run: false
tags:
 - flan-t5
 - augmented
batch_size: 8
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: google/flan-t5-base
output_root: models/flan-t5/
predict_batch_size: 2
augmented_ds: true

--- # ord first 5
config: ord_first_5
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - flan-t5
 - augmented
batch_size: 8
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: google/flan-t5-base
output_root: models/flan-t5/
predict_batch_size: 2
augmented_ds: true

--- # ft first 5
config: ft_first_5
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - flan-t5
 - augmented
batch_size: 8
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: google/flan-t5-base
output_root: models/flan-t5/
predict_batch_size: 2
augmented_ds: true

--- # ESSEL 6
config: essel_6
fast_dev_run: false
tags:
 - t5-base
 - fts_as_tokens
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
add_fts_as_tokens: true
predict_batch_size: 2

--- # ord first 6
config: ord_first_6
fast_dev_run: false
do_train: true
do_predict: true

tags:
 - t5-base
 - fts_as_tokens
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
add_fts_as_tokens: true
predict_batch_size: 2

--- # ft first 6
config: ft_first_6
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - fts_as_tokens
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
add_fts_as_tokens: true
predict_batch_size: 2

--- # ESSEL 7
config: essel_7
fast_dev_run: false
tags:
 - t5-base
 - simplify_ft_names
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_ft_names: true
predict_batch_size: 2

--- # ord first 7
config: ord_first_7
fast_dev_run: false
tags:
 - t5-base
 - simplify_ft_names
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_ft_names: true
predict_batch_size: 2

--- # ft first 7
config: ft_first_7
fast_dev_run: false
tags:
 - t5-base
 - simplify_ft_names
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_ft_names: true
predict_batch_size: 2

--- # ESSEL 7
config: essel_7
fast_dev_run: false
tags:
 - t5-base
 - simplify_ft_names
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_ft_names: true
predict_batch_size: 2

--- # ord first 7
config: ord_first_7
fast_dev_run: false
tags:
 - t5-base
 - simplify_ft_names
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_ft_names: true
predict_batch_size: 2

--- # ft first 7
config: ft_first_7
fast_dev_run: false
tags:
 - t5-base
 - simplify_ft_names
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_ft_names: true
predict_batch_size: 2

--- # ESSEL 8
config: essel_8
fast_dev_run: false
tags:
 - t5-base
 - simplify_qs
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_narr_qs: true
predict_batch_size: 2

--- # ord first 8
config: ord_first_8
fast_dev_run: false
tags:
 - t5-base
 - simplify_qs
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_narr_qs: true
predict_batch_size: 2

--- # ft first 8
config: ft_first_8
fast_dev_run: false
tags:
 - t5-base
 - simplify_narr_qs
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_narr_qs: true
predict_batch_size: 2

--- # ESSEL 9
config: essel_9
fast_dev_run: false
tags:
 - input_size_fix
 - t5-base
 - simplify_qs
batch_size: 4
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_narr_qs: true
max_features: 35
max_input_len: 500
predict_batch_size: 2

--- # ord first 9
config: ord_first_9
fast_dev_run: false
tags:
 - input_size_fix
 - t5-base
 - simplify_qs
batch_size: 4
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_narr_qs: true
max_features: 35
max_input_len: 500
predict_batch_size: 2

--- # ft first 9
config: ft_first_9
fast_dev_run: false
tags:
 - input_size_fix
 - t5-base
 - simplify_qs
batch_size: 4
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
simplify_narr_qs: true
max_features: 35
max_input_len: 500
predict_batch_size: 2

--- # text
config: text
fast_dev_run: false
tags:
 - t5-base
batch_size: 8
max_features: 15
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: t5-base
predict_batch_size: 2

--- # text 2
config: text_2
fast_dev_run: false
tags:
 - bart
batch_size: 8
max_features: 15
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2

--- # text 3
config: text_3
fast_dev_run: false
tags:
 - t5-base
batch_size: 8
max_features: 20
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: t5-base
predict_batch_size: 2

--- # text 4
config: text_4
fast_dev_run: false
tags:
 - bart
batch_size: 8
max_features: 20
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2

--- # text 5
config: text_5
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
 - augmented
batch_size: 8
max_features: 15
linearisation: text # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
predict_batch_size: 2
augmented_ds: true

--- # text 6
config: text_6
fast_dev_run: false
tags:
 - bart
 - augmented
batch_size: 8
max_features: 15
linearisation: text # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/bart-base/
predict_batch_size: 2
augmented_ds: true

--- # ESSEL test
config: essel_test
fast_dev_run: true
do_train: true
linearisation: text
max_features: 15
tags:
 - t5-base
batch_size: 4
simplify_narr_qs: true
