--- # ESSEL
config: essel
fast_dev_run: false
tags:
 - t5-base
batch_size: 8
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
output_root: models/qa/t5-base/
predict_batch_size: 2

--- # ord first
config: ord_first
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
batch_size: 32
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
output_root: models/qa/t5-base/
predict_batch_size: 2

--- # ft first
config: ft_first
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - t5-base
batch_size: 8
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: t5-base
output_root: models/qa/t5-base/
predict_batch_size: 2

--- # ESSEL 2
config: essel_2
fast_dev_run: false
tags:
 - bart
batch_size: 64
linearisation: essel # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/qa/bart-base/
predict_batch_size: 2

--- # ord first 2
config: ord_first_2
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
batch_size: 64
linearisation: ord_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/qa/bart-base/
predict_batch_size: 2

--- # ft first 2
config: ft_first_2
fast_dev_run: false
do_train: true
do_predict: true
tags:
 - bart
batch_size: 64
linearisation: ft_first # ['essel', 'ord_first', 'ft_first']
model_base: facebook/bart-base
output_root: models/qa/bart-base/
predict_batch_size: 2

--- # text
config: text
fast_dev_run: false
do_train: false
tags:
 - t5-base
batch_size: 32
max_features: 20
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: models/qa/t5-base/glamorous-wave-37/checkpoint-6750
version: hard # [normal, hard]
predict_batch_size: 2

--- # text 2
config: text_2
fast_dev_run: false
do_train: false
tags:
 - bart
batch_size: 32
max_features: 20
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: models/bart-base/fanciful-dragon-38/checkpoint-3750
output_root: models/qa/bart-base/
version: hard # [normal, hard]
predict_batch_size: 2


# NEW QnA ds
--- # text 3 
config: text_3
fast_dev_run: false
do_train: true
tags:
 - t5-base
batch_size: 16
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: t5-base
version: hard # [normal, hard]
predict_batch_size: 2

--- # text 4
config: text_4
fast_dev_run: false
do_train: true
tags:
 - bart
batch_size: 16
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: facebook/bart-base
output_root: models/qa/bart-base/
version: hard # [normal, hard]
predict_batch_size: 2

--- # text 5
config: text_5
fast_dev_run: false
do_train: true
tags:
 - t5-base
batch_size: 16
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: t5-base
version: hard # [normal, hard]
predict_batch_size: 2
num_epochs: 6

--- # text 6
config: text_6
fast_dev_run: false
do_train: true
tags:
 - bart
batch_size: 16
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: facebook/bart-base
output_root: models/qa/bart-base/
version: hard # [normal, hard]
predict_batch_size: 2
num_epochs: 6

--- # text 7
config: text_7
fast_dev_run: false
do_train: true
tags:
 - t5-large
batch_size: 2
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: t5-large
version: hard # [normal, hard]
predict_batch_size: 2

--- # text 8
config: text_8
fast_dev_run: false
do_train: true
tags:
 - bart-large
batch_size: 2
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
model_base: facebook/bart-large
output_root: models/qa/bart-base/
version: hard # [normal, hard]
predict_batch_size: 2

--- # ESSEL test
config: essel_test
fast_dev_run: true
do_train: true
batch_size: 32
max_features: 20
max_input_len: 400
linearisation: text # ['essel', 'ord_first', 'ft_first', text]
# model_base: facebook/bart-base
# output_root: models/qa/bart-base/
version: hard # [normal, hard]
