import copy
import functools
import re
import random
negative_singular = ['#fnegatives is the only feature shown to have negative contribution to the classification made here.',
                     'The correct label could be different from #pred_label given the attribution of #fnegatives. This input feature supports assigning an alternative label.',
                     'Among the input variables or features, the only one with influence decreasing the odds of the selected label, #pred_label is #fnegatives.',
                     'Decreasing the probability of the assigned label is the contribution of #fnegatives.',
                     'The model labels the given case as "#pred_label", however, the influence of #fnegatives  indicates otherwise.',
                     'The only input attribute indicating that the correct label could be different from the model\'s choice (#pred_label) is #fnegatives.',
                     'Any uncertainty associated with this classification could be attributed to the influence of #fnegatives.',
                     'With respect to the given classification decision above, the feature indicating otherwise is #fnegatives.',
                     'While all the input features positively supports the assigned label, #fnegatives indicates otherwise.',
                     'According to the attribution analysis, only #fnegatives has a negative influence or impact on the classification decision here.',
                     'Per the classification made here, analysis indicates that #fnegatives is solely responsible for the doubt in the final verdict.',
                     ]
negative_statements = ['The features with negative contribution to the prediction are #fnegatives.',
                       'The correct label or class of the given data could be different from #pred_label given the attribution of #fnegatives. These negative variables support assigning an alternative label.',
                       'Per the classification made here, analysis indicates that #fnegatives are solely responsible for the doubt in the final verdict.',
                       '#fnegatives have negative contributions to the classification made here.',
                       'The classification algorithm labels the given case as "#pred_label", however, the negative contributions of #fnegatives indicate otherwise.',
                       'Shifting the classification in a different direction are the influence of negative features #fnegatives.',
                       'The influence of negative features #fnegatives shift the classification in a different direction.',
                       'Driving the classifier to generate a different label are the negative features #fnegatives.',
                       'Instead of #pred_label, the values of variables or features #fnegatives drive the classification judgement in a different and opposite direction.',
                       'According to the attribution analysis, #fnegatives are the negative set of features reducing the model\'s response in favour of a different label.',
                       'Decreasing the prediction probability of the assigned label are the negative features #fnegatives.',
                       'The negative variables #fnegatives reduce the prediction probability of the chosen label (#pred_label).',
                       'Contributing negatively to the prediction are the features #fnegatives.',
                       'As per the classification model, the most appropriate label for the given case is #pred_label but contradicting this assertion are the values of #fnegatives',
                       '#fnegatives are referred to as "negative features" given that they negatively influence the model\'s prediction for the given case in favour of  a different label instead of the selected label.',
                       'The set of input variables reducing the prediction likelihood of the selected label are #fnegatives.',
                       ['Among the negative variables reducing the likelihood of the predicted label, #fnegative_top are the most negative compared to the influence of #fnegative_others.'],
                       ['The most negative features decreasing the odds of the assigned label are #fnegative_top. Other notable negative features include #fnegative_others.']
                       ]
negative_double = copy.deepcopy(negative_statements[:-2])
negative_double += [
    ['Among the negative variables reducing the likelihood of the predicted label, #fnegative_top is the most negative compared to the influence of #fnegative_others.'],
    ['The most negative feature decreasing the odds of the assigned label is #fnegative_top. The other notable negative feature is #fnegative_others.']

]

positive_singular = ['#fpositives is the only feature shown to have positive contribution in support of the classification made here.',
                     'The only feature shown to have positive contribution, shifting the classifier\'s decision in favour of #pred_label is #fpositives',
                     'Among the input variables, the only one with influence increasing the odds of the selected label, #pred_label,  is #fpositives.',
                     'Increasing the prediction probability of the assigned label (#pred_label) is the contribution of #fpositives.',
                     'The only input attribute indicating that the correct label is indeed the model\'s choice (#pred_label) here is #fpositives.',
                     'Any confidence or certainty associated with this classification decision is attributed to the positive influence of #fpositives.',
                     'With respect to the given classification decision above, the feature indicating otherwise is #fpositives.',
                     'While all the input features have negative influence contradicting the assigned label, #fpositives has a positive contribution in favour the decision made here.',
                     'According to the attribution analysis, only #fpositives has a positive influence or impact on the classification decision here.',
                     'Per the classification made here, analysis indicates that #fpositives is solely responsible for pushing the classifier towards the final verdict.',
                     'It is surprising the all the other features contradicts the classifiers decision while only #fpositives is shown to positive contribute to the assignment of #pred_label.'
                     ]


positive_statements = ['The features with positive contribution to the prediction are #fpositives.',
                       'From the attribution analysis, the set of features with positive contribution to the abovementioned classification are #fpositives.',
                       '#fpositives have positive influence on the classifier with respect to the classification made here.',
                       'The positive variables #fpositives increase the prediction odds of the chosen label (#pred_label).',
                       'Increasing the model\'s response in favour of the predicted class (#pred_label) are #fpositives.',
                       '#fpositives are referred to as "positive features" given that they positively  support the model\'s output prediction for the given case in favour of the selected label.',
                       'Shifting the prediction towards the above mentioned label are the positive features #fpositives.',
                       'According to the attribution analysis, #fpositives are the positive set of features enhancing the model\'s response in favour of the assigned label.',
                       'The set of input variables increasing the prediction likelihood of the selected label are #fpositives.',
                       ['Among the positive variables increasing the likelihood of the predicted or assigned label, #fpositive_top are the most positive compared to the influence of #fpositive_others.'],
                       ['According to the attribution investigation, the most positive features driving the classification towards the #pred_label label are #fpositive_top. Other features with similar direction of influence as #fpositive_top are #fpositive_others.'],
                       ['The most important positive features driving the classifier to assign the selected label are #fpositive_top. The least significant positive features include #fpositive_others.']
                       ]
positive_double = copy.deepcopy(positive_statements[:-2])
positive_double += [
    ['Among the positive variables increasing the likelihood of the predicted or assigned label, #fpositive_top is the most positive compared to the influence of #fpositive_others.'],
    ['The most important positive features driving the classifier to assign the selected label is #fpositive_top. The least significant positive feature include #fpositive_others.'],
    ['According to the attribution investigation, the most positive features driving the classification towards the #pred_label label is #fpositive_top. Other feature with similar direction of influence as #fpositive_top is #fpositive_others.'],
]

neutral_statements = ['The features with negligible contribution to the prediction are #fneutral.',
                      '#fneutral are referred to as "irrelevant features" given that they are shown to have negligible influence the model\'s prediction for the given case.',
                      'The irrelevant features in terms of the classification here are #fneutral.',
                      '#fneutral have insignificant influence on the algorithm with respect to the classification made here.',
                      'The irrelevant variables such as #fneutral have no impact on prediction odds of the chosen label.',
                      'When deciding on the correct label for the given data instance, the model paid little to no attention to the values of #fneutral.',
                      'To arrive at the classification decision here, #fneutral receive little emphasis or consideration.',
                      'For the assignment of #pred_label, #fneutral played very marginal role.',
                      'The values of #fneutral received very little consideration when the classifier was picking the most probable label for the given case.',
                      'Playing marginal role in arriving at the classification decision here are the features #fneutral.',
                      'The values of #fneutral are likely ignored by the model when making the labelling decision regarding the given case.',
                      '#fneutral are likely ignored by the classifier when making the classification with respect to the given case.',
                      'According to the attribution analysis, #fneutral have little to no influence on the model\'s response in favour or against of the assigned label.',
                      'The set of input variables with insignificant impact on prediction likelihood of the selected label are #fneutral.'
                      ]
neutral_statements_single = ['The feature with negligible contribution to the prediction is #fneutral.',
                             '#fneutral is referred to as "irrelevant" feature given that it is shown to have negligible influence the model\'s prediction for the given case.',
                             'The irrelevant feature in terms of the classification here is #fneutral.',
                             '#fneutral have insignificant influence on the algorithm with respect to the classification made here.',
                             'The irrelevant variable, #fneutral, have tittle to no impact on prediction odds of the chosen label, #pred_label.',
                             'When deciding on the correct label for the given data instance, the model paid little to no attention to the value of #fneutral.',
                             'To arrive at the classification decision here, #fneutral received little emphasis or consideration.',
                             'For the assignment of #pred_label, #fneutral played very marginal role.',
                             'Playing marginal role in arriving at the classification decision here is #fneutral.',
                             'The value of #fneutral is probably ignored by the model when making the labelling decision regarding the given case.',
                             '#fneutral is likely ignored by the classifier when making the classification with respect to the given case.',
                             'According to the attribution analysis, #fneutral has little to no influence on the model\'s response in favour or against of the assigned label.',
                             'The input variable with insignificant impact on prediction likelihood of the selected label is #fneutral.',
                             'The value of #fneutral received very little consideration when the classifier was picking the most probable label for the given case.',
                             ]


pred_statement_templates_uncertain_two_labels = [
    "It is important to note that the prediction verdict below is attributed to the contributions of mainly the input features. The model is not very certain about the true label for the case given.  Per the output prediction probabilities, there is an even split (prob_1 and prob_2) on the probability of either class_1 or class_2 is the correct label. But the model could simply assigns class_1 or class_2 to the case.",
    "There is uncertainty about the correct label for the given example. Any of the two labels (class_1 and class_2) is shown to have a pred_label_prob chance of being correct. ",
    "There is a prob_1-prob_2 chance that the prediction could be any of the two labels, class_1 and class_2. Based on the prediction probabilities, we can conclude that the model is uncertain about which label is the correct one. It could label the case as either class_2 or class_1. ",
    "There is a split on which label is appropriate for this case. The model is uncertain which of the two labels is the correct label. The uncertainty in the classification above can simply be attributed to the influence of some of the input variables.",
    "The model states that there is a prob_1 chance that the true label of this case is class_1 and a prob_2 chance that class_2 could be the true label. This indicates that the model is not compitent enough to correctly identify the true label since it demonstrates very high uncertainty in the prediction decision regarding the case under consideration.",
    "The classifier states that there is a prob_1 chance that the true label of this test observation is pred_label. This indicates that the classifier is less certain in its prediction decision regarding the case under consideration. The label assigned is mainly due to the values of the input features.",
    "Based on the predicted probabilities across the class labels, any of the labels could be the true label. Therefore, it can be concluded that the classifier is very uncertain about the best label choice for the given case considering the information provided.",
    "The classification algorithm indicates that any of the labels could be correct. To be specific, the algorithm is not able to settle on the best choice of label for the given case.",
    "Making prediction based on the information provided, the model was not able to decide which of the labels is the right choice since their respective probabilities are prob_1 and prob_2.",
    "Judging based on the prediction probabilities across the two classes, it is valid to conclude that the algorithm is unsure about which of the label is right for the given case.",
    "According to the prediction likelihood, there is a perfect split chance that either class_1 or class_2 is the right choice of label.",
    "Since there is a prob_1-prob_2 split on which label is best for the given case, the confidence level of the model can be termed as very low.",
    "It is vital to note that the final classification decision made here by the classifier is only based on the information provided about the given case. Judging based on the predicted likelihoods across the classes, it can be concluded that the classifier or model is unsure about which label is best for the given case.",
    "The model settled on label pred_label but it important to note that it is very uncertain about this decision judging based on the prediction probabilities between the classes.",
    "The classifier states that there is a prob_1 chance that the true label of this case is class_1 and a prob_2 chance that class_2 could be the true label. This indicates that the classifier failed to identify the correct label since it is less certain in its prediction decision regarding the case under consideration.",
]

pred_statement_templates_two_labels_uncertain = ["The model makes classification decisions based on the information provided to it. For the case here, the prediction probabilities across the two class labels, class_1 and class_2, are prob_1 and prob_2, respectively. Based on these prediction probabilities, the label assigned is pred_label, since it has the highest likelihood. However, the model is not very certain about the correctness of the assigned label since its probability is marginally higher than the average. The uncertainty in the classification here could be blamed on some subset of the input features that have negative attributions that decrease the prediction probability of the assigned label.",
                                                 "The label assignment here is based on the information supplied to the classifier. According to the classifier, the prediction probability of class_1 is prob_1 whereas that of class_2 is prob_2. Hence pred_label is chosen as the most probable label over invalid_1. However, it is concerning that the classifier is not very certain about this verdict given that the difference between the two probabilities is very small. The uncertainty in the classification decision can be attributed to the influence of some of the input features.",
                                                 "The classification decision below is based on the information provided to the classifier about the case under review. The case under consideration is labelled as pred_label with a modest level of confidence because the probability that invalid_1 is the correct label is approximately invalid_1_prob. Further analysis could reveal the set of features resulting in the prediction probabilities across the labels.",
                                                 "The algorithm labels the data given as pred_label and the prediction probabilities across the possible labels class_2 and class_1, respectively, are prob_2 and prob_1. Judging based on the prediction probabilities, the algorithm shows some signs of uncertainty in the above decision which further investigations could reveal the variables that indicate that either of the two labels could be the true label.",
                                                 "This model trained on this classification task generates the class label pred_label for this case with a confidence level equal to pred_label_prob, suggesting that the likelihood of invalid_1 being the correct label is invalid_1_prob. Overall, the confidence level of the model with respect to this case is not as high as one might expect.",
                                                 "The case under consideration is labelled as pred_label by the model employed for this classification problem. However, according to the model, there is a invalid_1_prob chance that invalid_1 could be the label presenting some level of uncertainty in the classification verdict made here.",
                                                 "There is a pred_label_prob chance that the label is pred_label, whereas there is a invalid_1_prob likelihood that invalid_1 is the correct label. The uncertainty of the model in terms of this case or instance can be attributed mainly to the direction of influence of the input variables. Further investigation will reveal which features are shifting the classification towards invalid_1 away from pred_label.",
                                                 "According to the model, pred_label is the class with the highest probability (pred_label_prob) of being the label for this selected instance or case. Conversely, there is a invalid_1_prob chance that invalid_1 is the correct label. This shows that the model is somewhat  uncertain about the classification verdict in this case. ",
                                                 "The final classification made was pred_label, but with a likelihood of only pred_label_prob. Given that there is a invalid_1_prob chance that the true label could be invalid_1, the model's certainty with respect to the classification output is a somewhat questionable.",
                                                 "The model predicted pred_label with pred_label_prob likelihood, with the other class (invalid_1) only being slightly lower at invalid_1_prob. The confidence level of the model with respect to this classification decision is not as high as one might expect given the prediction likelihoods across the two classes.",
                                                 "For the given case or instance,  the model assigns the label pred_label, with the prediction confidence equal to pred_label_prob. It is important to also note that there is a invalid_1_prob chance that the alternative label invalid_1 could be the correct label. Based on the prediction probabilities or odds across the classes, the confidence level of the model in terms of the classification made here can be described as moderate but it is somewhat certain that pred_label is the most probable label for the given case.",

                                                 ]
pred_statement_templates_two_labels_marginal_doubt = [

]
pred_statement_templates_two_labels = [
    "Since the predicted likelihood of class invalid_1 is only invalid_1_prob, the model predicted pred_label as the most likely label for the given case with high prediction probability of approximately pred_label_prob.",
    "The model prediction for the test case is pred_label, and the confidence level of this prediction decision is close approximately pred_label_prob since the prediction probability of invalid_1 is only invalid_1_prob.",
    "For the given data instance, the label assigned by the classifier is pred_label since it has a prediction probability of about pred_label_prob. On the other hand, there is a invalid_1_prob chance that invalid_1 could be the appropriate label.",
    "The case given is labelled as pred_label by the classifier with a confidence level equal to pred_label_prob. Therefore, the probability of invalid_1 being the correct label is only invalid_1_prob. The classification above is mainly due to the information provided about the case under investigation.",
    "The following classification statements are based on the case information supplied to the prediction model. Class pred_rank_2 has a prediction probability of pred_rank_2_prob, whereas class pred_label has a prediction value of pred_label_prob. As a result, it is correct to deduce that pred_label is the most likely label for the given case.",
    "There is a pred_label_prob chance that pred_label is the true label for the given case, indicating that the prediction probability of invalid_1 is only invalid_1_prob. Based on the abovementioned classification probabilities, pred_label is selected as the most probable label with a pretty high confidence level.",
    "It is vital to note that the final classification decision made here by the classifier is only based on the information provided about the given case. With a high level of confidence, the classifier labels the given case as pred_label since the prediction probability of invalid_1 is equal to invalid_1_prob.",
    "Here the classifier labels the given case as pred_label with a fairly high confidence level. Specifically, the prediction likelihood of class invalid_1 is only invalid_1_prob. The main drivers for the classification above the information supplied to the classifier about the case under investigation.",
    "With respect to the information supplied about the current case under consideration, in this instance, the classification model generated the label pred_label with a prediction probability equal to pred_label_prob. What this imply is, the likelihood of invalid_1 being the true label is only invalid_1_prob less than average hence the model has a very high confidence or certainty level.",
    "This data instance is labelled as pred_label with a high confidence level equal to pred_label_prob since the prediction likelihood of invalid_1 is only invalid_1_prob. The confidence in the classification above is attributed to the information provided about the data instance.",
    "The prediction algorithm is moderately certain that the most probable label for the given data is pred_label. However, there is also a invalid_1_prob possibility that invalid_1 could be the correct label. Any doubt in the classification here can be attributed to the direction of influence of some of the input features supplied to the prediction algorithm.",
    "The label assigned by the classifier to the case under consideration is pred_label. This is mainly based on the fact that the prediction likelihood of invalid_1 is only invalid_1_prob, meaning the classifier is confident that pred_label is the right label. The high certainty in the abovementioned classification could largely based on the certain group of features among the information passed as the classifier's input.",
    "Based on the values of the input variables, the prediction model labels the case given as pred_label with very high certainty. Specifically, there is only about a invalid_1_prob possibility that invalid_1 is the correct label according to the model. ",
    "The model is not convinced that the correct label for the data under consideration is invalid_1 since there is a pred_label_prob chance that labelling the data as pred_label is correct. In other words, since pred_label has a higher prediction probability than invalid_1, it is selected as the most likely label for the case here.",
    "The classification or prediction algorithm indicates that the most probable label for the given data instance is pred_label but it is important to note that there is a invalid_1_prob chance that invalid_1 could be the true label.",
    'The classifier made the prediction here based on the information provided about the case under consideration. According to the classifier, the prediction probabilities or likelihoods across the labels class_1 and class_2 are prob_1 and prob_2, respectively. From these prediction probabilities, it is without a doubt that the true label is likely pred_label. All the input features have different degrees of influence on the final decision here by the classifier.',
    "The model decides on the true label for the given case depending on the information presented to it. Per the model employed here, the prediction probability of invalid_1 is only invalid_1_prob, and that of pred_label is equal to pred_label_prob. Given the information provided to the model, the most valid conclusion regarding the true label is that pred_label is without a doubt the most likely one. The attributions analysis can identify  the major drivers (variables) resulting in the prediction probabilities across the classes under consideration.",
    "The final decision of the classifier on the true label with respect to the given case is based on the information provided to it. The classifier produced the following prediction probabilities: prob_2 and prob_1, respectively, for class_2 and class_1. From the prediction probabilities, pred_label is choosen by the classifier as the most probable label, and pred_label_prob indicates the confidence level.",
    "The classification algorithm's decision with respect to the actual label for the given case is mainly dependent on the information presented to it. According to the algorithm, the prediction likelihood of class_2 is prob_2, while that of class_2 is prob_1. As a result, the actual label for the case under consideration is most likely pred_label, and the invalid_1_prob likelihood of invalid_1 represents only the level of uncertainty in the classification algorithm's decision. Further analysis can reveal which of the input variables are causing the uncertainty in the classification decision here.",
    "According to the information supplied about the case under consideration, the model outputs pred_label as the most probable label since the prediction probability of invalid_1 is only invalid_1_prob. Therefore, there is a invalid_1_prob doubt on the side of the model when it comes to which of the two labels is the true label for the given case. ",
    "Judging based on the information provided on the case under consideration, the model outputs that the prediction probability of invalid_1 is only invalid_1_prob, indicating that with about pred_label_prob certainty, the true label here is pred_label. In simple terms, the model is pred_label_prob confident that the true label for the case under consideration is pred_label. The degree of certainty in the above classification could be attributed solely to the positive contributions of some of the most influential features.",
    "For the case under consideration, the model's output labelling decision is as follows: (a) The possibility that invalid_1 is the label for the given case is low; (b) pred_label is the most likely class label, with a confidence level close to pred_label_prob. All these came about based on the information on the case given to the model.",
    "The prediction decision made here came about based on the information provided to the classification model. The prediction likelihoods across the two classes are as follows: (a) pred_label_prob for class pred_label, (b) invalid_1_prob for class invalid_1. From the above, it can be concluded that pred_label is the most probable class label (with a higher degree of confidence) for the given data instance.",
    "Label invalid_1 has a lower probability than label pred_label, so pred_label is the most likely option in this case. pred_label has a prediction probability of approximately pred_label_prob, which can be attributed to the different variables taken into consideration by the classification model.",
    "The likelihood of label invalid_1 is lower compared to that of label pred_label; hence, the most probable label for the given case is pred_label. The prediction probability of pred_label is about pred_label_prob, and it can be attributed to the values of features passed to the classification algorithm. The confidence level of the algorithm can be termed very high since the prediction probability of the assigned class is far higher than average.",
    "According to the classification model employed here, the most probable label for the given case is pred_label with a confidence level equal to pred_label_prob. In simple terms, there is a invalid_1_prob possibility that pred_label is not the true label.",
    "The most probable label for the given case is pred_label since its associated prediction probability is pred_label_prob compared to the invalid_1_prob of invalid_1. Based on the prediction probabilities across the class labels, the classification model's certainty is verified to be greater.",
    "For the case given here, the prediction decision is as follows: (a) The probability of class_1 being the correct label is only prob_1. (b) The probability of pred_label is pred_label_prob, making it the most probable label for the case here. The prediction model's confidence can be deemed greater than average, with a likelihood of pred_label_prob.",
    "With respect to the given case, the classification algorithm employed here generates pred_label as the most probable class since the probability of invalid_1 is invalid_1_prob while that of pred_label is pred_label_prob.",
    "pred_label is the right class label for the given case mainly due to the contributions and impacts of the input variables on the model employed here. According to the model, the probability of class_1 is prob_1 and that of class_2 is prob_2 meaning pred_label is the most probable label for the given case.",
    "Based on the input variables, the model is moderately confident that the pred_label is the appropriate label for the data under consideration. In fact, the prediction likelihood associated with class invalid_1 is about invalid_1_prob. The abovementioned classification decision can be largely blamed on the contributions of different information about the classifier.",
    "pred_label is the most probable label with respect to the case under consideration since the prediction likelihood of the other label, invalid_1, is only invalid_1_prob. The above classification verdict is based on the different attributions of the variables on the classifier employed in this instance.",
    "According to the final prediction probabilities across the two classes, invalid_1 and pred_label, the output decision for the given data is pred_label with a pred_label_prob confidence level. invalid_1 has a prediction probability of about invalid_1_prob hence can't be considered as the true label.",
    "The prediction probability of class class_1 is prob_1 while that of class_2 is only prob_2. From the above, it is obvious that pred_label is the most probable label for the case under consideration. The classification decision made here is mainly due to the contributions of different variables considered by the model about the case under consideration.",
    "The classification decision summarised below is mainly due to the contributions of different variables considered by the classifier about the given. For the given case, the classifier outputs the label pred_label instead of invalid_1, since pred_label has a higher prediction likelihood than invalid_1. According to the classifier the likelihood of pred_label is pred_label_prob far greater than that of invalid_1.",
    "The predicted label is pred_label and the confidence level as indicated by the prediction probability is pred_label_prob.  The high confidence can be attributed to the contributions of the different variables supplied about the data instance.",
    "Since the predicted probability of invalid_1 is invalid_1_prob, the predicted label is pred_label and the confidence level as indicated by the prediction probability is pred_label_prob.  The high confidence can be attributed to the contributions of the different variables supplied.",
    "The classification model employed made its label selection decision based on the information provided about the case under consideration. With a higher degree of confidence, it classifies the case under consideration as pred_label. Specifically, per the model, the probability of labelling the case as \"invalid_1\" is equal to invalid_1_prob, hence not as likely as pred_label.",
    "Judging based on the values of the input variables, the classification algorithm labels the case as pred_label with a quite high certainty since its prediction likelihood is equal to pred_label_prob. In simple terms, there is only invalid_1_prob likelihood that the true label is invalid_1.",
    "The data under consideration is labelled as \"pred_label\" since it is the most probable label, with a prediction likelihood equal to pred_label_prob. This implies that the classifier employed here (judging based on the information supplied) is confident that invalid_1 is not the right or true label.",
    "The given case is labelled as \"pred_label\" since it has a prediction probability of pred_label_prob meaning the alternative possible label, invalid_1, is the least probable one (with prediction likelihood of invalid_1_prob). The higher confidence in the assigned label is mainly due to the contributions of the input features.",
    "It is important to recognise that the final classification decision made by the model here is only based on the values of the features of the case under consideration. The odds of invalid_1 being the correct label for the given case is about invalid_1_prob since the likelihood of pred_label according to the model is pred_label_prob.",
    "The prediction verdict here is that the most probable class label is pred_label. In fact, the classification algorithm indicates that there is only invalid_1_prob possibility that the correct or true label is invalid_1.",
    "The final classification decision here is solely based on the information on the data instance provided to the prediction model employed. The predicted label predicted for the case under consideration is pred_label_prob, with a fairly high confidence level. Specifically, the chance of invalid_1 being the correct label is only invalid_1_prob.",
    "Judging based on the values of the input features, the classifier labels the given data as\"pred_label\" with a prediction confidence equal to pred_label_prob. This suggests that the prediction likelihood of invalid_1 is only invalid_1_prob which less than the likelihood of pred_label.",
    "Considering the values of the input variables or features, for this case, the classification model's confidence is about pred_label_prob, implying that the likelihood of label invalid_1 is about invalid_1_prob. ",
    "Considering the values of the input variables or features, the classification algorithm employed here is confident that the most probable label is not invalid_1 but pred_label. Specifically, according to the algorithm, there is invalid_1_prob chance that invalid_1 is the true label for the given case based on the information supplied.",
    "pred_label is assigned as the label for the given data with high confidence level equal to pred_label_prob. Therefore, according to the classification algorithm, there is likely little to no chance that invalid_1 is the right label for this case.",
    "The model predicted that the example should be classified as pred_label with a pred_label_prob likelihood. In addition, the model also identified that there was a invalid_1_prob chance that the right label could actually be invalid_1. Therefore it can be concluded that there is only a marginal doubt in the classification decision made here.",
    "The model predicted pred_label for the case under consideration with the prediction confidence level of about pred_label_prob, suggesting that on the other hand, there is a invalid_1_prob chance that invalid_1 could be the accurate label instead.",
    "For the case under consideration, the model assigned pred_label with quite high confidence equal to pred_label_prob suggesting that the likelihood of invalid_1 being the right label is small (in fact equal to invalid_1_prob).",
    "The model predicts class label pred_label for the case under review with a high certainty. There is only invalid_1_prob chance that the appropriate label is invalid_1.",
    "The model predicted pred_label_prob likelihood of the class label pred_label for the case or data under consideration. On other hand, there is invalid_1_prob chance that the correct class label could be a different label. ",
    "For this test case, the model predicts pred_label with about pred_label_prob certainty. In fact the prediction probability associated with label invalid_1 is only equal to invalid_1_prob. ",
    "The model predicts class pred_label with about pred_label_prob confidence meaning the probability that invalid_1 is the right label is only about invalid_1_prob. Based on the prediction probabilities across the classes, the model can be decribed as being certain that invalid_1 is not the correct label here.",
    "The classification model or algorithm employed here predicts produces pred_label as the correct label for the given data instance with pred_label_prob confidence therefore there only invalid_1_prob chance that invalid_1 could be the accurate label considering likelihoods or odds.",
    "According to the classifier, the correct label for the given case is likely pred_label with a confidence level of pred_label_prob. However, it is important to note that there is also a invalid_1_prob possibility that invalid_1 could be the correct label. The classification assertions above were arrived at mainly due to the influence and contributions of the different input variables.",
    "The classifier produces pred_label as the true label for the given instance with a likelihood of about pred_label_prob, and invalid_1 with only a likelihood of around invalid_1_prob. This means the classifier is confident in its classification.",
    "The classifier is  pred_label_prob certain that the given case is under the class label pred_label since the probability that invalid_1 is the true label is about invalid_1_prob. From the above, the confidence level in the final labelling decision of pred_label can be termed as quite high. ",
    "The classification assertions arrived here are mainly based on the influence and contributions of the different input variables. The prediction probabilities across the two classes pred_label and invalid_1 are pred_label_prob and invalid_1_prob, respectively. Therefore according to the classifier, the most likely class label for the case under investigation is pred_label and it is quite sure that invalid_1 is not the true label here.",



]
pred_statement_templates_three_labels = [
    "Considering the values of the input variables or features, for this case, the classification model's confidence in the predicted label, pred_label, is about pred_label_prob. Looking at the likelihood of label invalid_1 and invalid_2, the model is sure that none of them is the true label. ",
    "The probability or likelihood of any of the classes class_1, class_2, and class_3 being the correct label is given as prob_1, prob_2, and prob_3, respectively. Therefore, it can be concluded that the most likely label for this case is pred_label. The above prediction decision is based on the values of the features.",
    "Per the algorithm, there is, respectively, pred_rank_3_prob, and pred_rank_2_prob chance that the true label for the given data instance is any of the following classes: pred_rank_3 and  pred_rank_2. In summary, the algorithm is quite certain that the true label is indeed pred_label.",
    "The algorithm employed to perform the classification predicts class pred_label with a likelihood of around pred_label_prob and class invalid_1 with a likelihood of around invalid_1_prob. Besides, the algorithm does not think invalid_2 is very likely, leaving a final prediction decision as pred_label.",
    "The case given is labelled as pred_label by the classifier with a confidence level equal to pred_label_prob. Therefore, the probability of invalid_1 being the correct label is only invalid_1_prob whereas that of invalid_2 is equal to invalid_2_prob. The classification above is mainly due to the information provided about the case under investigation.",
    "The classifier labels the given example as pred_label with a confidence level equal to pred_label_prob. As a logical consequence, the likelihood of invalid_1 being the proper label is only invalid_1_prob, but invalid_2 has a probability of invalid_2_prob. The aforementioned classification is primarily based on the evidence supplied concerning the case under investigation.",

    "The following classification statements are based on the case information supplied to the prediction model. Class class_1 has a prediction probability of prob_1, that of class_3 is prob_3, whereas class class_2 has a prediction likelihood of prob_2. As a result, it is correct to deduce that pred_label is the most likely label for the given case.",
    "The classification assertions that follow are based on the case information provided to the prediction model. Class class_1 has a prediction probability of prob_1, class_3 has a prediction probability of prob_3, and class_2 has a prediction probability of prob_2. In the nutshell, we can conclude that pred_label is the most possible label for the current case under review.",

    "According to the classifier, pred_label is the most probable label, followed by pred_rank_2 and pred_rank_3. To be specific, the prediction probabilities across the classes are as follows: class_1 (prob_1), class_2 (prob_2), and class_3 (prob_3). The moderately high classification confidence could largely be due to the impact of certain input features supplied to the classifier.",
    "Per the classifier, the most likely label is pred label, whereas the least likely ones being pred_rank_3 and pred_rank_2. The prediction probabilities for each class is as follows: class_1 (prob_1), class_2 (prob_2), and class_3 (prob_3). The classification confidence is attributed to the influence of certain input variables provided to the classifier.",

    "With a moderately high level of confidence, the classifier labels the given case as pred_label. This is due to the fact that the other classes, invalid_1 and invalid_2, have likelihoods of invalid_1_prob and invalid_2_prob, respectively. The aforementioned assertions are mostly attributable to the case information provided to the classifier.",
    "The classifier identifies the provided example as pred_label with a relatively high level of confidence. This is because the other classes, pred_rank_3 and pred_rank_2, have probabilities of pred_rank_3_prob and pred_rank_2_prob, respectively. The preceding statements are primarily attributed to the information provided about the case under consideration.",

    "Judging based on the information provided about this data instance, the prediction likelihoods across the three labels, class_3, class_2, and class_1, respectively, are prob_3, prob_2, and prob_1. Therefore, the prediction model outputs pred_label as the most probable label since the other labels have lower likelihoods.",
    "Based on the data supplied for this data instance, the model predicts that the likelihoods for the three labels pred_rank_2, pred_label, and pred_rank_3 are pred_rank_2_prob, pred_label_prob, and pred_rank_3_prob, respectively. As a result, because alternative labels are unlikely, the predictive model produces pred_label as the most likely.",

    "The prediction findings are as follows: (a) The probability that pred_label is the correct label is pred_label_prob, (b) The probability that invalid_1 is the correct label is invalid_1_prob, and (c) The probability that invalid_2 is the correct label is invalid_2_prob. Judging based on the prediction probabilities across the classes, pred_label is the most probable label. The confidence in the assigned label can be attributed varying level of influence of the input features.",
    "Confidence in the model's label choice is attributed to varying degrees of contributions of input features. The label selection findings are: (a) the probability that pred_label is the correct label pred_label_prob, (b) the probability that pred_rank_2 is the correct label pred_rank_2_prob, and (c) the probability that pred_rank_3 is the correct label pred_rank_3_prob. From the predicted likelihoods of the classes, pred_label is chosen as most likely one.",

    "prob_3, prob_2, and prob_1, respectively, are the chance or likelihood of any of the classes class_3, class_2, and class_1 being the appropriate label for the case given here. As a result, it's safe to say that pred_label is the most likely label for this situation. The values of the attributes or variables were considered to make the aforementioned prediction choice.",
    "The values ​​of the attributes or variables were considered for the prediction output verdict below. prob_1, prob_3, and prob_2 are the odds or probabilities that any of the classes class_1, class_3, and class_2 is the true label for the case or example under investigation. Consequently, we can safely say that pred_label is the probable class label in this situation. ",

    "The classification algorithm arrived at the prediction output based on the variables or information supplied about the case under consideration. The prediction probabilities across the three-class labels, class_1, class_2, and class_3, respectively, are prob_1, prob_2, and prob_3. Therefore, the label assigned by the algorithm, judged based on the prediction probabilities, is pred_label. However, the other labels are also shown to be somewhat likely to a certain degree.",
    "For this classification problem, the algorithm generates a predictive output based on the variables or information provided about the given data instance. The predicted probabilities of the threelabels class_3, class_1, and class_2 are prob_3, prob_1, and prob_2, respectively. Therefore, the label selected by the algorithm determined according to the prediction probability is pred_label. Conversely, other labels also show some potential of being the true label.",

    "The classification model's decision about the true label for the case is based on the information provided to it. All the input features have different degrees of influence on the final decision here by the model. Among the three labels, class_1, class_2, and class_3, the model shows without a doubt that neither invalid_1 nor invalid_2 is the true label, given that the probability of pred_label being the true label is pred_label_prob.",
    "The decision of the classification model about the true label of the case given is based on the information supplied to it. The input features have varying degrees of contributions to the final decision of the model here. Between the three labels class_1, class_2 and class_3, the probability that pred_label is the true label is pred_label_prob, hence, the model unambiguously states that neither invalid_1 nor invalid_2 is the true label.",

    "The classification algorithm predicts class pred_label, with a likelihood of around pred_label_prob, invalid_1, with around invalid_1_prob, and invalid_2 with around invalid_2_prob. It is fairly confident of its pred_label classification decision and is certain that the label for the case under consideration is neither class invalid_1 nor invalid_2.",
    "The class prediction algorithm outputs pred_label, with a prediction probability about pred_label_prob. For the other labels, the predicted probability of  invalid_1 is invalid_1_prob, and that of invalid_2 is invalid_2_prob. Here, the algorithm has confident in its pred_label classification decision and agrees that none of the other label is the correct one.",

    "The below-mentioned classification judgement is primarily based on the factors or features of the given case. The class label for this case is estimated to be pred_label out of the three potential classes, with a high probability of pred_label_prob. The next likely label is pred_rank_2, which has a probability of roughly pred_rank_2_prob. The classifier, on the other hand, is positive that pred_rank_3 isn't the accurate or true label.",
    "The following classification decisions are largely based on the factors or attributes of this particular case. The class label in this case is projected to be pred_label out of the three potential classes, which is likely pred_label_prob. The next possible label is pred_rank_2, which has an approximate probability of pred_rank_2_prob. The model, however, affirms that pred_rank_3 is not the true label.",

]





pred_statement_templates_four_labels = [
    "The values of the attributes or variables were considered to make the prediction  choice. prob_3, prob_2, and prob_1, respectively, are the chance or likelihood of any of the classes class_2, class_2, and class_1 being the appropriate label for the case given here. As a result, it's safe to say that pred_label is the most likely label for this situation.",
    "With a pred_label_prob level of confidence, the model labels the given case as pred_label. This is due to the fact that the other classes, invalid_1, invalid_3, and invalid_2, have likelihoods of invalid_1_prob, invalid_3_prob and invalid_2_prob, respectively. The aforementioned assertions are mostly attributable to the case information provided to the model.",
    "The label for this case is estimated to be pred_label out of the four potential classes, with a high probability of pred_label_prob. The next likely label is pred_rank_2, which has a probability of roughly pred_rank_2_prob. The classifier, on the other hand, is positive that neither pred_rank_3 nor pred_rank_4 is the accurate or true label. The aforementioned judgement is mostly based on the factors or features of the given case.",
    "Per the algorithm, there is, respectively, pred_rank_3_prob, pred_rank_2_prob, and pred_rank_4_prob chance that the correct label for the given data instance is any of the following classes: pred_rank_3, pred_rank_2, and pred_rank_4. In summary, the algorithm is quite confident that the true label is pred_label.",
    "The classification algorithm arrived at the prediction output based on the variables or information supplied about the case under consideration. The prediction probabilities across the four-classes, class_1, class_4, class_2, and class_3, respectively, are prob_1, prob_4, prob_2, and prob_3. Therefore, the label assigned by the algorithm, judged based on the prediction probabilities, is pred_label. However, it is important to consider the likelihoods of the remaining labels, pred_rank_2, pred_rank_3, and pred_rank_4.",
    "Based on the information provided about the case under consideration, model indicates that pred_rank_4 and pred_rank_3 have the lowest prediction probabilities, while that of pred_rank_2 is pred_rank_2_prob (hence neither of them could be the true label), meaning the most probable label is pred_label (with approximately pred_label_prob certainty). ",
    "According to the classification algorithm, neither pred_rank_3 nor pred_rank_2 nor pred_rank_4 is the true label for the given case. It is pred_label_prob certain that pred_label is the right label. The degree of certainty in the above prediction can be attributed to the impact of the different input features considered.",
    "The degree of certainty in the prediction decision made with respect to the given case can be attributed to the impact of the different input features considered. The model predicted the pred_label class for the test case with a high degree of confidence. In fact, the prediction probabilities of invalid_1, invalid_2, and invalid_3 are all lower than pred_label_prob, meaning that it is confident that neither of these three labels is the correct one.",
    "Between the four possible classes, the label for this case is predicted as pred_label, with a pred_label_prob likelihood that this is correct. With a likelihood of about pred_rank_2_prob, the next probable label is pred_rank_2 and, the classifier is also certain that neither pred_rank_3 nor pred_rank_4 is the true or correct label. The prediction assessment above is mainly based on the variables or attributes of the given case.",
    "The prediction model classifies the case under consideration as \"pred_label\" with a likelihood of about pred_label_prob. However, there is about a invalid_2_prob chance that the true class label is invalid_2. In addition, it is confident that invalid_1 or invalid_3 is not the true label since they have lower prediction probabilities.",
    "The model predicts class pred_label with almost pred_label_prob certainty, indicating the model is very confident that it is correct label. This indicates that neither invalid_1 nor invalid_3 nor invalid_2 is the right label since they have very low probabilities than compared to pred_label. ",
    "With a higher level of confidence, the case under consideration is labelled as pred_label. In simple terms, the chance of any other label is lower. The certainty of the classifier can primarily be traced to the influence of the information supplied about the data instance.",
    "The classier predicted the pred_label class for the test case with a high degree of confidence. In fact, the prediction probabilities of invalid_1, invalid_2, and invalid_3 are all lower than pred_label_prob, meaning that it is confident that neither of these three labels is the correct one.",
    "The label assigned by the classification model is pred_label,  and the confidence level is pred_label_prob. The reason for the certainty assertion is that there is a pred_rank_2_prob chance that it could be pred_rank_2; a pred_rank_3_prob chance that it could be pred_rank_3 and a pred_rank_4_prob chance that it could be pred_rank_4 according to the model. Overall, the least probable label is pred_rank_4.",
    "The proceeding classification output observations are based on the information provided about this particular case. The class label in this case is projected to be pred_label out of the four potential labels, with a likelihood of about pred_label_prob. The next possible label is pred_rank_2, which has an approximate probability of pred_rank_2_prob, the third possible label with a likelihood of pred_rank_3_prob is pred_rank_3. The algorithm, however, affirms that pred_rank_4 is not the true label.",
]
